openapi: 3.0.3
info:
  title: Hotel Booking API
  description: This API allows to book and edit hotel reservations.
  version: 1.0.0
tags:
 - name: New booking
   description: Allows to create a new booking with the guest's info. 
paths:
  /hotels/bookings:
    post:
      tags:
       - New booking
      summary: This service allows to create a new hotel booking
      description: Creates a booking for the specified hotel and dates.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Booking details
          schema:
            type: object
            required:
              - hotelId
              - checkInDate
              - checkOutDate
              - guests
              - preferences
            properties:
              hotelId:
                type: string
                description: Unique identifier of the hotel
                example: "hilton001"
              checkInDate:
                type: string
                format: date
                description: Check-in date in YYYY-MM-DD format
                example: "2023-12-28"
              checkOutDate:
                type: string
                format: date
                description: Check-out date in YYYY-MM-DD format
                example: "2024-01-05"
              guests:
                type: array
                items:
                  type: object
                  required:
                    - name
                    - email
                    - phone
                  properties:
                    name:
                      type: string
                      description: Guest's full name
                      example: "John Doe"
                    email:
                      type: string
                      format: email
                      description: Guest's email address
                      example: "johndoe@gmail.com"
                    phone:
                      type: string
                      description: Guest's phone number
                      example: "+57301234567890"
              preferences:
                type: object
                properties:
                  smoking:
                    type: boolean
                    description: Preference for smoking or non-smoking room
                    example: false
                  bedType:
                    type: string
                    description: Desired bed type (e.g., "king", "queen", "twin")
                    example: "queen"
      responses:
        '201':
          description: Booking created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  bookingId:
                    type: string
                    description: Unique identifier of the booking that the service created
         '400':
          description: The system could not process the request due to missing or erroneous data
               
  
